# Generated by Django 4.0.2 on 2022-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.IntegerField(default=100, verbose_name=1000),
        ),
    ]
